### PR TITLE
Update runtime to 47.0

### LINKED ISSUE #29: Update runtime to 47
This is needed for the app follow the user accent-color.

### PR DESCRIPTION
**Pull request by A6GibKm**
Fixes: https://github.com/flathub/org.gnome.Polari/issues/29

### CODE REVIEW

**Comment by A6GibKm** [comment]
Build fails because these licenses are being installed https://gitlab.gnome.org/GNOME/polari/-/blob/main/data/icons/hicolor/scalable/apps/org.gnome.Polari.Devel.svg.license?ref_type=heads.

**Comment by fmuellner** [comment]
Sigh, quel surprise, reuse getting in the way again :-(

I opened https://gitlab.gnome.org/GNOME/polari/-/merge_requests/321 which should fix the issue.

**Comment by fmuellner** [comment]
Thanks!

**Comment by A6GibKm** [comment]
Note that starting the app without any app data (e.g. deleting the folder under .var) will print a bunch of g_warnings for me, but I think they are unrelated to this MR.

**Comment by A6GibKm** [comment]
Thanks!

**Pull request merged**
